// Package llm defines the LLM interface for calling OpenAI-compatible chat
// completion APIs, along with request/response types and error classification.
package llm

import (
	"context"
	"fmt"
	"time"
)

// LLM is the interface for calling an OpenAI-compatible chat completion API.
// Streaming is deferred to v2 — v1 is non-streaming only.
type LLM interface {
	// Call sends a chat completion request and returns the full response.
	// The caller's ctx controls cancellation and timeout.
	Call(ctx context.Context, req Request) (Response, error)
}

// Request holds all parameters for a single chat completion call.
type Request struct {
	Model     string
	BaseURL   string
	APIKey    string     // auth token for the request (resolved from env var by main.go)
	Messages  []Message
	Tools     []ToolDef
	MaxTokens int
}

// Response holds the model's reply, including any tool calls (function calls)
// generated by the model, and token usage statistics.
type Response struct {
	Text      string     // The model's text reply (empty if only tool_calls)
	ToolCalls []ToolCall // Parsed tool calls, if any
	Usage     TokenUsage
}

// Message represents a single message in the chat conversation.
// A single type serves all four roles — the caller sets only the fields
// relevant to the current role:
//   - "system": Content only
//   - "user": Content only
//   - "assistant": Content and/or ToolCalls
//   - "tool": Content and ToolCallID
type Message struct {
	Role       string     // "system" | "user" | "assistant" | "tool"
	Content    string
	ToolCallID string     // non-empty only when Role == "tool"
	ToolCalls  []ToolCall // non-empty only when Role == "assistant"
}

// ToolDef describes a function tool that the model may call.
type ToolDef struct {
	Function ToolFunction `json:"function"`
}

// ToolFunction is the definition of a callable function, including its
// JSON Schema for parameters.
type ToolFunction struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Parameters  any    `json:"parameters"` // JSON-serializable schema object
}

// ToolCall represents a function call emitted by the model.
type ToolCall struct {
	ID       string          `json:"id"`
	Function ToolCallFunction `json:"function"`
}

// ToolCallFunction contains the name and arguments of a function call.
// Arguments is a raw JSON string that must be unmarshalled by the caller.
type ToolCallFunction struct {
	Name      string `json:"name"`
	Arguments string `json:"arguments"` // raw JSON string
}

// TokenUsage tracks token consumption for a request.
type TokenUsage struct {
	PromptTokens     int
	CompletionTokens int
	TotalTokens      int
}

// ---------------------------------------------------------------------------
// Error classification for retry/backoff (§8 of spec)
// ---------------------------------------------------------------------------

// ErrorCategory distinguishes error types so Phase 3's retry/backoff logic
// can act on the category without inspecting provider-specific error internals.
type ErrorCategory int

const (
	ErrCategoryUnknown    ErrorCategory = iota // unclassified/unexpected (was ErrCategoryOther)
	ErrCategoryTimeout                          // context deadline or HTTP timeout
	ErrCategoryRateLimit                        // HTTP 429
	ErrCategoryQuota                            // insufficient_quota / HTTP 403 or 429 with quota body
	ErrCategoryAuth                             // HTTP 401 (bad API key), 402/403 non-quota
	ErrCategoryMalformed                        // 200 OK but response body is garbled/empty
)

// LLMError wraps an error with a category and optional metadata.
type LLMError struct {
	Err        error
	Category   ErrorCategory
	RetryAfter time.Duration // populated only for ErrCategoryRateLimit (from Retry-After header)
	StatusCode int           // HTTP status code, 0 if not an HTTP error
}

func (e *LLMError) Error() string {
	return fmt.Sprintf("llm: %s (category=%d, http=%d)", e.Err.Error(), e.Category, e.StatusCode)
}

// Unwrap returns the wrapped error so errors.Is/errors.As can traverse the chain.
func (e *LLMError) Unwrap() error {
	return e.Err
}
